### ISSUE TITLE
Power up .vol 1

### ISSUE THREAD

**Issue by Tsuchiya2** [Toita3n/expired-foods#26]
これから就活に向けて、webアプリをパワーアップしていきましょう！

以下の部分に手を入れましょう。

#### ■ヘッダー
- お問い合わせ・利用規約・プリバシーポリシー・使い方ガイド・コピーライトの部分：縦に連なって表示される形になっていますが、横幅に応じて横並びにするなど、レスポンシブ対応しましょう。

#### ■ユーザー登録画面
![スクリーンショット 2023-12-05 20 24 30](https://github.com/Toita3n/expired-foods/assets/61481161/beaaf2b6-ed30-4912-83f6-5e2efa60a311)

#### ログイン画面
![スクリーンショット 2023-12-05 20 34 35](https://github.com/Toita3n/expired-foods/assets/61481161/f1c4bfe3-5680-464e-a54c-363652f3bd5b)

#### ユーザー詳細
![スクリーンショット 2023-12-05 20 48 27](https://github.com/Toita3n/expired-foods/assets/61481161/f35d96e6-3c6e-4dd0-8123-d46475640314)

#### 買い物リスト
エラーが出ているのでレビューできない箇所があります。そちらの調査・修正もお願いします。
<img width="691" alt="スクリーンショット 2023-12-05 23 39 06" src="https://github.com/Toita3n/expired-foods/assets/61481161/e627c8fc-7750-4e16-924c-f17070f6359a">

#### 商品一覧（商品一覧ではなく、冷蔵庫の中身に変更してください）
ヘッダーの商品登録の項目は削除してください。
冷蔵庫の中身ページから"食材の記載"をクリックすると、登録が行えるようにしてください。
（商品・食材といった表記も修正。"食材の記載"と齟齬が無いように統一感があるように修正してください）
<img width="984" alt="288082604-796a2a73-9b7b-4daf-95d3-ea6de1c69212" src="https://github.com/Toita3n/expired-foods/assets/61481161/8d0876be-108c-4e04-b4d1-e5281dbfea62">

#### 食材の記載
<img width="984" alt="スクリーンショット 2023-12-06 0 06 11" src="https://github.com/Toita3n/expired-foods/assets/61481161/5c44edc5-a842-4c9e-aa34-d5ec91f556eb">

#### ??詳細??
<img width="994" alt="スクリーンショット 2023-12-06 0 14 21" src="https://github.com/Toita3n/expired-foods/assets/61481161/1c990b42-a8bb-4c5f-88d0-ba0cc540609b">

#### 色づかい
・寒色系の色は食材関係では使用しない方が良いらしいので寒色系の色はベースから外しましょう。
・黒・白を基調としているようですので、暖色系であと1色多くても2色で構成するなど、使用する色は検討し直してください。
・使用している背景グレー、寒色系のブルーはオシャレにも映らず、サービスの印象を低下させているように感じたので、他の食材系に関わるサービスのWebページなどを調べて、どういう構成・色使い・使用している色数などを調査して、本アプリにもそれを活かしてください。

#### トップページ
<img width="993" alt="288090886-f4afe6b8-0b2f-4e6c-a86c-876c819a4282" src="https://github.com/Toita3n/expired-foods/assets/61481161/4510add6-5dd1-4d0c-a268-c489d08865e8">

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
1週間後を目処にレビューしますので、完了次第ご連絡ください。
よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
Mattermostに投稿されていた質問を以下に記載しておきます。

```
商品・食材一覧
　 商品数の+と-ボタンの一の変更の仕方がわかりません.
　cssでdisplayをflexにしてみましたが,変わりませんでした。

商品・食材登録
　a.詳細の部分に重量や重さなどを表示したいと思っていますが、こちらでは問題があるでしょうか？
　b.詳細で買った場所を記述する理由は、調味料など久しぶりに買おうとした時に難度がこの調味料はどこで買ったか思い出せないこともあるという現象もあったので、買った場所などがわかると再び買いに行けると思っていたため記述しています。
　c. テンプレートの使用は以前MVP reviewにて、'商品名は概ね決まったものは初期から選択するだけで良いようにした方が入力の手間を省けてユーザーに優しい'とおっしゃっていたので作成しました。　別のものがいい場合はご教示ください。
```

**Comment by Tsuchiya2** [comment]
> 商品・食材一覧
商品数の+と-ボタンの一の変更の仕方がわかりません.
cssでdisplayをflexにしてみましたが,変わりませんでした。

Bootstrapを使用しているようですので、その辺りからどうしたら横に表示できるのか、検証ツールを使って、どんなcssが対象の要素に当たっているかを確認して、影響を確認しながら指摘していた形に表示されるように試行錯誤してみてください。

> 詳細の部分に重量や重さなどを表示したいと思っていますが、こちらでは問題があるでしょうか？

文面だけでは上記の質問がよく分からなかったので推測を込みでので回答になりますが...重量や重さなどは一覧ページに表示する形にしましょう。個々の詳細ページに遷移しないと、必要な情報を確認できないように現状なっているので、複数の項目の重量等を確認するには、詳細→一覧→詳細→一覧→...と手間が多く、ユーザーに不便な体験となっています。修正しましょう。思いつきのアイディアですが、一覧から対象の項目（卵など）をクリックした際に、モーダル表示でその辺りの情報を表示させるとかだと遷移の手間が無いので、ユーザーに優しい体験になるかと思います。

> 詳細で買った場所を記述する理由は、調味料など久しぶりに買おうとした時に難度がこの調味料はどこで買ったか思い出せないこともあるという現象もあったので、買った場所などがわかると再び買いに行けると思っていたため記述しています。

問題に感じている点は、数量を入力する箇所はあれど、食材は1つ1つと数えられないものがあるため、それを買った場所等のごちゃ混ぜな情報が入力できるフォームの形になっている箇所です。容量・重さなどは別個に切り出して入力できるようにしてください。↑のようなものを想定しているのであれば'詳細'ではなく、'メモ'が適切ではないでしょうか？

> テンプレートの使用は以前MVP reviewにて、'商品名は概ね決まったものは初期から選択するだけで良いようにした方が入力の手間を省けてユーザーに優しい'とおっしゃっていたので作成しました。　別のものがいい場合はご教示ください。

このPower upのissueを記載した際に、テンプレート部分をクリックしましたが、何も変化が無かったため、それを受けてのコメントでした。実装がまだ途中でしたら失礼しました。引き続き開発を進めていただければと思います。

---

上記来週までに取り組んでいただき、来週の今日(火曜日)に進捗の共有をお願いいたします。

**Comment by Toita3n** [comment]
お忙しい中お返事ありがとうございます
```
このPower upのissueを記載した際に、テンプレート部分をクリックしましたが、何も変化が無かったため、それを受けてのコメントでした。実装がまだ途中でしたら失礼しました。引き続き開発を進めていただければと思います。
```
テンプレートに関しては現在キャッシュを削除してみたら機能したので問題ないかと思われます。
　室温時効が出たら再度お願いします。 今後ともよろしくお願いします。

**Comment by Toita3n** [comment]
お世話になっております。 現在の状況を記述します。

直したもの：
1. ユーザー登録画面とログイン画面の文字やフォームの位置の変更
2. ユーザー登録画面で白枠が出ないようにしました
3. 背景の色を変更しました
4. ヘッダーから商品登録を削除
5. 冷蔵庫の中身から概要検索の削除
6. 写真登録、表示機能の削除
7. 冷蔵庫の中身での詳細ページをモーダル表記に変更
8. +と-ボタンの位置の変更
9. 食材・商品登録でテンプレートを使用できるようにしました
10. 全ての登録画面で強調表示の変更
11. tagの削除

直していないもの：
1. shopping_listsの複数登録の実装
2. LINE関連の不具合
3. ユーザーアカウントのモーダル記述

以下に今週直面した問題点の質問です。

1.本番環境のDBにおけるエラー
　現在ゲストユーザーのところにある'卵'の商品が削除できなくなっています。 AWS内のproduction.logを見たところ
```
 SELECT `active_storage_attachments`.* FROM `active_storage_attachments` WHERE `active_storage_attachments`.`record_id` = 15 AND `active_storage_attachments`.`record_type` = 'Item' AND `active_storage_attachments`.`name` = 'image' LIMIT 1
D, [2023-12-18T12:09:47.173991 #32520] DEBUG -- : [a6e9155a-8a00-45c0-8e24-a86daafe3b6b]   Item Destroy (1.1ms)  DELETE FROM `items` WHERE `items`.`id` = 15
D, [2023-12-18T12:09:47.177389 #32520] DEBUG -- : [a6e9155a-8a00-45c0-8e24-a86daafe3b6b]   TRANSACTION (3.2ms)  ROLLBACK
I, [2023-12-18T12:09:47.177777 #32520]  INFO -- : [a6e9155a-8a00-45c0-8e24-a86daafe3b6b] Completed 500 Internal Server Error in 12ms (ActiveRecord: 6.7ms | Allocations: 1451)
F, [2023-12-18T12:09:47.178425 #32520] FATAL -- : [a6e9155a-8a00-45c0-8e24-a86daafe3b6b]   
[a6e9155a-8a00-45c0-8e24-a86daafe3b6b] ActiveRecord::InvalidForeignKey (Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`expired_foods`.`item_tags`, CONSTRAINT `fk_rails_2774a12fa0` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`))):
```
と表示されているので、tag機能の名残が残っているため削除ができていないようです。 本番環境はテーブルを削除しない方がいいと思われますが、行っても良いものなのでしょうか?
行っても良いなら
https://qiita.com/iczo32/items/84719b5aff8a6b9e37bd
こちらを参考にDBのリセットを行いたいと思っています。

2.shopping_listsの複数のレコードの同時登録について
　こちらは商品が登録されましたと表示されますが、DBを確認すると何もDBに内容が入っていません。
https://qiita.com/kinop1987/items/63586892116446043365
こちらの記事を参考にしてやってみました。個人的にformの書き方が、sign_up_form.rbと違い、shopping_list自体の定義がないから登録が入っていないのかおしれないと思っています。申し訳ありませんが、長いこと詰まっているのでヒントをお願いします。

3. アカウント詳細画面について
![image](https://github.com/Toita3n/expired-foods/assets/119268064/00cc8d86-992f-4d96-950a-3ec17cbc708f)
こちらのモーダル表記にするようにと書かれていますが、モーダル表記にする理由を聞いてもよろしいですか？　現在は以下のようにしています。
![image](https://github.com/Toita3n/expired-foods/assets/119268064/5a844b73-8a2a-4a39-a1a6-3ac09a4fc1ef)

お忙しい中長文失礼しました。よろしくお願いします。

**Comment by Tsuchiya2** [comment]
進捗共有ありがとうございます。
まずは3つの質問から回答します。

> 1.本番環境のDBにおけるエラー

ユーザー数も少ないかと思うので削除してしまって構いません。アクティブなユーザー(毎日使用しているユーザー)が入れば、その方には事情を伝えておくのが良いかと思いますが、そうしたユーザーがいないのであれば影響も少ない＆使用されていないデータなので削除するというのも選択肢としては致し方ないかと思います。その方向で進めてください。

> 2.shopping_listsの複数のレコードの同時登録について

手元で検証ツール(gem 'pry-rails')を入れて値を確認したら、すぐに登録できました。pry-railsを入れた後、binding.pryを使って、関連コードの値を確認してみてください。必須のカラムに全て値が渡っているかよくよく確認・検証してみてください。


> 3.アカウント詳細画面について

ページ遷移した割に、あまり情報が少ないので遷移の手間を省く提案になります。優先度は他のものに比べて高くは無いので、他のものを優先する形で大丈夫です。

現状の該当ページを触れてですが、Line Account Exits?は表示されていて大丈夫でしょうか？その文字列に連携済みか連携を促すリンクを表示するほうが良さそうです。

<hr />

- shopping_listsの複数登録の実装
- LINE関連の不具合
- ユーザーアカウントのモーダル記述

上記に加えて以下もお願いします。商品・食材登録・霊ぞこの中身、初期よりは良くなってきていますが、まだ手を入れたほうが良さそうなので以下に記載します。

・数、賞味期限も他の項目と同じ用に項目が上、入力箇所は下に配置するようのしましょう。統一感は大切です。
<img width="661" alt="スクリーンショット 2023-12-19 22 33 14" src="https://github.com/Toita3n/expired-foods/assets/61481161/68ede4aa-25c7-4881-ba3c-0822fcddcf59">

・数の増減のボタンと数量表示が近すぎるかと思います。また、横一直線に見た際に、行が凸凹しているように見えて、やや崩れている印象を見ている側に与えてしまいます。食材を基準に一直線に全てが収まるようにしましょう。カレンダーのアイコンや時計のアイコンも左上にせず、「◯ 2023-12-25」といった形にしましょう。数の増減のボタンも同様です。
<img width="676" alt="スクリーンショット 2023-12-19 22 38 30" src="https://github.com/Toita3n/expired-foods/assets/61481161/28b3e58f-8cff-4ff1-b649-ce3ece7742b8">
<img width="676" alt="スクリーンショット 2023-12-19 22 39 57" src="https://github.com/Toita3n/expired-foods/assets/61481161/17799aad-1c9e-49f8-af4a-bdd5cccbe5b2">

=== 追記 ===
・一括登録のチェックボックスの有り無しで登録されるか否かはページ上は分からなかったので、チェックボックスが無くても記入したものは登録される方が良いかと。初見のユーザーからすると、チェックボックスの意味がわからないですし、チェックボックスにチェックを入れる手間は余計に感じるかと思います。

**Comment by Toita3n** [comment]
お返事ありがとうございます。 買い物リストについてです。私はbyebugを利用しているのですが、
```
 Started POST "/shopping_lists" for ::1 at 2023-12-20 11:41:57 +0900
Processing by ShoppingListsController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "shopping_list_collection_form"=>{"shopping_lists_attributes"=>{"0"=>{"product"=>"そば", "number"=>"21", "trait"=>""}, "1"=>{"product"=>"とり", "number"=>"2", "trait"=>""}, "2"=>{"product"=>"うめ", "number"=>"4", "trait"=>""}, "3"=>{"product"=>"はぎ", "number"=>"5", "trait"=>""}, "4"=>{"product"=>"シュークリーム", "number"=>"5", "trait"=>""}}}, "commit"=>"商品・食材登録"}
  User Load (15.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`id` = 11 LIMIT 1
  ↳ app/controllers/application_controller.rb:13:in `current_user'

[11, 20] in /Users/sasatai/workspace/runteq/original_app/expired-foods/app/controllers/shopping_lists_controller.rb
   11: 
   12:   def create
   13:     @shopping_list = ShoppingListCollectionForm.new(shopping_list_collection_params)
   14:     if @shopping_list.save
   15:       byebug
=> 16:       redirect_to shopping_lists_path, success: t('.success')
   17:     else
   18:       flash.now[:danger] = t('.fail')
   19:       render :new
   20:     end
(byebug) @shopping_list
#<ShoppingListCollectionForm:0x000000013c229ad8 @shopping_lists=[#<ShoppingList id: nil, product: "そば", number: 21, trait: "", created_at: nil, updated_at: nil, user_id: nil>, #<ShoppingList id: nil, product: "とり", number: 2, trait: "", created_at: nil, updated_at: nil, user_id: nil>, #<ShoppingList id: nil, product: "うめ", number: 4, trait: "", created_at: nil, updated_at: nil, user_id: nil>, #<ShoppingList id: nil, product: "はぎ", number: 5, trait: "", created_at: nil, updated_at: nil, user_id: nil>, #<ShoppingList id: nil, product: "シュークリーム", number: 5, trait: "", created_at: nil, updated_at: nil, user_id: nil>]>
```
上記のものを見る限り入っているようにも思えません。また、shoppingList idがnilになっているのが調べてもわかりません。 どうやらuser_idが入っていないようなのですが、入らなくなり理由がわかりません。申し訳ありませんが、ヒントをお願いします。

**Comment by Tsuchiya2** [comment]
app/forms/shopping_list_collection_form.rb にもbyebugを入れて確認すると良いかと思います。

> どうやらuser_idが入っていないようなのですが

↑こちらの着眼点は良いかと思います。user_idに値を渡してあげて保存できれば良いのではないかと思います。

おそらくcurrent_userをshopping_list_collection_form.rbで使えないかと思いますので、汚いやり方で言えばsaveメソッドにログインしているユーザーのインスタンスを渡すようにして、shopping_list保存前にuser_idカラムに引数で渡ってきたユーザーのインスタンスIDを格納してあげれば良さそうです。

**Comment by Toita3n** [comment]
お世話になっております。 現在の状況を記述します。
直したもの：
 1.　DBの再作成
 2. 食材・商品登録画面での入力場面での統一感を出すようにする
 3. 冷蔵庫の中身でのレイアウトの変更
 4. shopping_listでの複数登録ができるようにする（現在１０種類の商品を同時登録可能）
 5. LINE関連の不具合
 6. LINEの自作公式アカウントとのトーク内で　冷蔵庫　と入力するとそのユーザーが登録しているitemを全て表示できるように
 
以下、一つだけ気になったので質問です。
１.　商品登録画面で最初labelで項目を表示するのではなく、全てplaceholderにしようと思ったのですが、賞味期限のところだけplaceholderが機能しなかったため断念しました。 どうやら、date typeだとただplaceholderと記述したとしても反映されないとのことでしたので、この場合はjavascriptを使ったり、直接htmlのinputから変更する方法しかないのでしょうか？

お忙しい中失礼しました。　精査のほどよろしくお願いします。

**Comment by Tsuchiya2** [comment]
状況共有ありがとうございます。
まずは質問に関して回答します。

> １.　商品登録画面で最初labelで項目を表示するのではなく、全てplaceholderにしようと思ったのですが、賞味期限のところだけplaceholderが機能しなかったため断念しました。 どうやら、date typeだとただplaceholderと記述したとしても反映されないとのことでしたので、この場合はjavascriptを使ったり、直接htmlのinputから変更する方法しかないのでしょうか？

=> placeholderの件ですが、賞味期限は入れなくてもクリックして選択すれば良いというのがユーザーも分かるので、全てに入れなくても良いかと思います。javascript等でそこへに注力するより、以下の改善部分に注力いただく方が効果が高いかと思いますので、取り組みをお願いいたします。

---

##### アプリを触っての改善点

■トップページの修正
・写真付きでの投稿ではなくなったので、トップページも修正しておきましょう。どんな風に使うかが分かるようにトップページを作り込むと、ユーザーもどういったアプリをこれから触るのかが分かってアプリ体験がよくなるかと思います。
・修正の際に、LINEの連携の説明文が画像からはみ出しているように映ってしまうため、その辺りも統一性をもたせて表示させましょう。
![スクリーンショット 2023-12-27 15 07 22](https://github.com/Toita3n/expired-foods/assets/61481161/4de26db6-897c-4b2d-bdad-aa862893a6a0)

■アカウント作成画面のフォーム幅の修正
・入力の右側が妙に空間があってバランスが悪い印象を与えるものになっているので、以下の画像辺りまで入力フォームを伸ばしましょう。（ログイン画面も同様です）
![スクリーンショット 2023-12-27 15 09 32](https://github.com/Toita3n/expired-foods/assets/61481161/afa53410-b5ba-438f-9439-beebd0e5d571)

■ヘッダーの表示の順番変更
・ログアウトが一番左側にあるのは、Webアプリのサービスにおいてあまり無いケース＆よく使うものほど、左から順番に並べることが多いため、以下の順番に修正しましょう。

- 冷蔵庫の中身
- 商品・食材登録
- 買い物リスト
- アカウント設定
- ログアウト（ヘッダーから表示を無くす・アカウント情報ページにボタン等でログアウトできるようにする）
![スクリーンショット 2023-12-27 15 13 42](https://github.com/Toita3n/expired-foods/assets/61481161/4efda9bc-afbb-4a7e-810d-40e02a902617)

■商品・食材登録
・テンプレート選択箇所の文言が長すぎて、スマホだとフォームからはみ出してしまっているので、「テンプレート」という表記だけに修正しましょう。
・また、上から順番に入力を行っていった後に、テンプレートを選択するという動線になっているので、一番上部にテンプレート選択箇所、同行に「テンプレート使用」ボタンを並べて表示させましょう。（「テンプレート使用」ボタンと「テンプレート」との間には適切な空間を設けましょう）
・商品名・数・賞味鬼面げの入力フォームもバラバラになっているので、以下の画像のように右側が揃っているなどの統一性をもたせましょう。（項目のところは統一性が出ていてGoodです）
・メモ欄ですが、横長に書くより縦に箇条書きで記載していく方が使い勝手及び見栄えも良いかと感じました。text_areaに変更、カラムもstring型であったならtext型に修正しましょう。
・商品・食材の編集ページも同様に対応をお願いします。
![スクリーンショット 2023-12-27 15 21 58](https://github.com/Toita3n/expired-foods/assets/61481161/52adc75e-af95-4b63-9f4c-0bb8f585d768)

■買い物リスト一覧ページの修正
・登録されたものを削除できる、新しく登録できるのは確認ができましたが、編集＆更新はできない想定で良かったでしょうか。
・食材名をクリックすると編集ページに遷移するとかしても良いかと思いました。（理想は画面遷移せず編集ホームがポップアップで表示され、更新すると非同期で変わるのが望ましいですが、難しい場合はそれ用の編集ページを用意して更新でも可です）
![スクリーンショット 2023-12-27 15 49 33](https://github.com/Toita3n/expired-foods/assets/61481161/5e3fb354-91b1-41cc-90c6-29c5f2e088a1)

■買い物リストに標品を追加ページの修正
・現状、表のようなもので登録をさせようとしているのは分かりますが、特徴とそれ以外の入力フォームが異なるため、チグハグな印象を与えるものになっています。（"特徴"に関しても開発者以外は何を入力する欄なのかが分からない開発者善がりのものになってしまっています。改善してください。）
・スマホサイズにするとページ崩れも起こしているようなので、根本の改善が必要そうです。
![スクリーンショット 2023-12-27 15 52 23](https://github.com/Toita3n/expired-foods/assets/61481161/c3b4b316-2cae-4bda-9a8f-466ee64bff99)
・合わせて改善案を以下の画像に記載しました。
![スクリーンショット 2023-12-27 15 51 31](https://github.com/Toita3n/expired-foods/assets/61481161/32ce1172-6d81-481c-9902-f644775219db)

■共通
・どのページもですが、ヘッダーに各ページで表示されるコンテンツが近すぎるため、ヘッダー要素から少し離れた箇所からコンテンツ表示させるようにしましょう。
・買い物リスト入力の際に気づきましたが、PCサイズだけでなく、タブレットやスマホサイズでも画面が崩れていないかチェックをして改善をお願いします。

**Comment by Toita3n** [comment]
お世話あになっております。以下直したところを記述したいと思います。
直した部分
１. トップページの修正(写真の変更と追加。また、写真はoverflow-xを使用しました)
２. アカウント作成およびログイン時の入力フォームの幅の修正
3. 商品・食材登録でのテンプレートボタンなどの位置調整
4. 買い物リストで更新できるように変更
5. 変更する時には商品名をクリックするとモーダル表記で編集画面を出すようにしました。
6. 買い物リストをスマホに対応させました。
7. ユーザーガイドの写真と内容を変更しました。
8. ヘッダーからほんの少し、コンテンツから離しました。

以下質問です。
ヘッダーにログアウトを以前としてつけているのですが、位置を1番右に変えてみました。 アカウント設定のページにロウアウトしようとするたびに経由しないといけないのは面倒かと思われましたが、ヘッダーはやめた方が良いのでしょうか？

お忙しい中、長文読んでいただきありがとうございました。

**Comment by Toita3n** [comment]
追加で、質問です。
アカウント情報の部分でスマホ対応させようとしたところ、左によっているように思われます。 
![a84c1650c88b46b403fa60e552e1d67a](https://github.com/Toita3n/expired-foods/assets/119268064/afecc6a4-6750-470a-b32f-9bc2eca1abbc)

このような状況の場合、cssを見直すべきだと思ったので、profile.scssの.tableの横幅を変更しようとしたのですが、変化がなかったようなので、このような場合、tableというよりその親要素であるdiv classを変更するべきなのでしょうか？ 簡単な質問かもしれませんが、ご回答の程よろしくお願いします。

**Comment by Tsuchiya2** [comment]
> ヘッダーにログアウトを以前としてつけているのですが、位置を1番右に変えてみました。 アカウント設定のページにロウアウトしようとするたびに経由しないといけないのは面倒かと思われましたが、ヘッダーはやめた方が良いのでしょうか？

<img width="1171" alt="スクリーンショット 2024-01-10 16 35 04" src="https://github.com/Toita3n/expired-foods/assets/61481161/4a8f5df9-f4ef-43b7-be9e-23e16e9e8871">

確認しました。そうですね...変更前よりは良いかと感じました。これもありかと思いますので現状で進めましょう。

---

> このような状況の場合、cssを見直すべきだと思ったので、profile.scssの.tableの横幅を変更しようとしたのですが、変化がなかったようなので、このような場合、tableというよりその親要素であるdiv classを変更するべきなのでしょうか？ 

検証ツールを使うと、どの部分の要素を変更すれば良いかの見立てがたてられるかと思うので試してみてください。

<img width="774" alt="スクリーンショット 2024-01-10 17 06 21" src="https://github.com/Toita3n/expired-foods/assets/61481161/bda96be3-bb8b-442f-a38c-292f4e134832">


<img width="774" alt="スクリーンショット 2024-01-10 17 07 39" src="https://github.com/Toita3n/expired-foods/assets/61481161/f2eb7e67-3bf7-4384-babd-6c618422a50c">

**Comment by Toita3n** [comment]
風邪は完治していませんが、以前質問していた質問をおいておきます。

1. 以前ユーザー詳細画面としていたアカウント情報をモーダル化する必要性が、知りたいです。 
　このページは以前としてモーダル化をした方がよろしいのでしょうか？必要であるのならば変更します。

**Comment by Tsuchiya2** [comment]
![スクリーンショット 2024-01-18 16 16 57](https://github.com/Toita3n/expired-foods/assets/61481161/67806a87-1acc-4645-a205-40120734b06a)

こちらで指摘したものですね。見落としておりすみませんでした🙇‍♂

指摘当時は見た目・使いにくさのマイナス要素から可能な限り底上げをとの考えからレビューしましたが、現状のアプリ全体からするとモーダル化しなくても良いくらいまで改善されているので、モーダル化は行わなくて良いかと思います。（細かい修正まで対応いただき、ありがとうございます）

全体として、やや印象を下げてしまうのは買い物リストの入力フォーム部分くらいになってきていますので、そちらの対応を体調と相談しながら進めていただければと思います。

よろしくお願いいたします。
